### ISSUE TITLE
Is there a branch that we can use with XCode 8 / Swift 3?

### ISSUE THREAD

**Issue by QiuZhiFei** [AlertKit/AlertKit#2]

**Comment by thii** [comment]
The `master` branch.

**Comment by igor9silva** [comment]
The issue is the latest tag (0.1.3 was released in April), not the branch (which is updated to Swift 3).

We just need a newer tag. Can you create one @thii, please?

**Comment by igor9silva** [comment]
As a workaround, CocoaPods allows the use of commit hashes, as following: 
`pod 'AlertKit', :git => 'https://github.com/thii/AlertKit.git', :commit => 'a897212'`
